project_id = "fzyonvqyiaoblhhzkybj"

[functions.generate-summary]
verify_jwt = false

[functions.analyze-ats]
verify_jwt = false

[functions.enhance-description]
verify_jwt = false

[functions.adapt-cv]
verify_jwt = false

[functions.generate-cover-letter]
verify_jwt = false